#        arguments: [@service_id, "plain_value", %parameter%]

parameters:
    paveldacar_accounts_keeper.date_formatter.class: Paveldacar\AccountsKeeperBundle\Utils\DateFormatter

services:
    paveldacar_accounts_keeper.date_formatter:
        class: %paveldacar_accounts_keeper.date_formatter.class%
