<?php

namespace Paveldacar\AccountsKeeperBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ExpenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseRepository extends EntityRepository
{
    /**
     * @param string $month
     * @param string $year
     * @return array
     */
    public function findByMonth($month, $year){
        $queryBuilder = $this->createQueryBuilder('expense');

        $this->filterByMonth($queryBuilder, $month, $year);

        $query = $queryBuilder->getQuery();

        return $query->getResult();
    }

    /**
     * @param string $month
     * @param string $year
     * @return array
     */
    public function countTotalByMont($month, $year)
    {
        $queryBuilder = $this->createQueryBuilder('expense');

        $this->filterByMonth($queryBuilder, $month, $year);

        $queryBuilder->select('SUM(expense.cost)');

        $query = $queryBuilder->getQuery();

        return $query->getSingleScalarResult();
    }

    /**
     * @param QueryBuilder $queryBuilder
     * @param string $month
     * @param string $year
     * @return QueryBuilder
     */
    public function filterByMonth($queryBuilder, $month, $year)
    {
        $queryBuilder->where('MONTH(expense.spentAt) = :month')
            ->andWhere('YEAR(expense.spentAt) = :year')
            ->setParameter('month', $month)
            ->setParameter('year', $year);

        return $queryBuilder;
    }
}
